/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.RoleSelection.Admin;

import Business.Course.Course;
import Business.Course.CourseList;
import Business.Degree.DegreeList;
import Business.Professor.Professor;
import Business.Professor.ProfessorList;
import Business.ProfessorLogin.ProfessorLogin;
import Business.ProfessorLogin.ProfessorLoginList;
import Business.Student.Student;
import Business.Student.StudentList;
import Business.StudentLogin.StudentLogin;
import Business.StudentLogin.StudentLoginList;
import UserInterface.RoleSelection.MainJFrame;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Random;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;                                                          

/**
 *
 * @author nasik
 */
public class ReportPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    MainJFrame frame;
    ProfessorList professorList;
    ProfessorLoginList professorLoginList;
    CourseList courseList;
    StudentList studentList;
    StudentLoginList studentLoginList;
    JPanel userProcessConatiner;
    DegreeList degreeList; 
    HashMap<String, List<Course>> studentCour;

    /**
     * Creates new form ReportPanel
     */

    public ReportPanel(JPanel userProcessContainer, ProfessorList professorList, ProfessorLoginList professorLoginList, CourseList courseList, StudentList studentList, StudentLoginList studentLoginList, HashMap<String, List<Course>> studentCour, DegreeList degreeList) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.professorList= professorList;
        this.professorLoginList= professorLoginList;
        this.courseList = courseList;
        this.studentList =studentList;
        this.studentLoginList = studentLoginList;
        this.studentCour =studentCour;
        this.degreeList = degreeList;
       
        populateReportTable();
    }

    public HashMap<String, List<Course>> getStudentCour() {
        return studentCour;
    }

    public void setStudentCour(HashMap<String, List<Course>> studentCour) {
        this.studentCour = studentCour;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblReport = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 204));

        btnBack.setBackground(new java.awt.Color(204, 204, 255));
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblReport.setBackground(new java.awt.Color(204, 204, 255));
        lblReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReport.setText("REPORT");

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Course - ID", "Student Name", "Course Registered", "Professor Name", "Grade", "Fees"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(lblReport, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(lblReport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void populateReportTable() {
        DefaultTableModel model = (DefaultTableModel) tblReport.getModel();
        model.setRowCount(0);
        
//        for(Student s: studentList.getStudentList()){
//            ArrayList<Course> regCourses = (ArrayList<Course>) studentCour.get(s.getStudentName());
//            for(Course c: regCourses){
//                Object[] row = new Object[5];
//                row[0] = s.getStudentName();
//                row[1] = c.getCourseName();
//                row[2] = c.getProfCName();
//                row[3] = c.getFee();
//                row[4] = s.getGPA();
//                
//                model.addRow(row);
//            }
//        }
    
    List<String> grades = new ArrayList<>();
    Collections.addAll(grades, "A", "A-", "B", "B-");
    Random rand = new Random();
    
    List<String> fuss = new ArrayList<>();
    Collections.addAll(fuss, "1200", "1000", "1400", "1600");
   
    for (int i = 0; i < courseList.getCourseList().size(); i++){
        Course c = courseList.getCourseList().get(i);
        Student s = studentList.getStudentList().get(i);
        
         int randomIndex = rand.nextInt(grades.size());
         int randumIndex = rand.nextInt(fuss.size());
         
        Object[] row = new Object[6];
        row[0] = c; 
        row[1] = s;
        row[2] = c.getCourseName();
        row[3] = c.getProfCName();
        row[4] = grades.get(randomIndex);
        row[5] = fuss.get(randumIndex);
        
        model.addRow(row);
    }
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblReport;
    private javax.swing.JTable tblReport;
    // End of variables declaration//GEN-END:variables
}
