/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import personProfile.Person;
import personProfile.PersonDirectory;

/**
 *
 * @author nasik
 */ 
public class CreatePersonJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    /**
     * Creates new form CreatePersonJPanel
     */
    CreatePersonJPanel(JPanel userProcessContainer, PersonDirectory personDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblLicenseNum = new javax.swing.JLabel();
        txtLicenseNum = new javax.swing.JTextField();
        lblHomeAdrHeader = new javax.swing.JLabel();
        lblHomeStreetAdr = new javax.swing.JLabel();
        txtHomeStreetAdr = new javax.swing.JTextField();
        lblHomeUnitNum = new javax.swing.JLabel();
        txtHomeUnitNum = new javax.swing.JTextField();
        lblHomeCity = new javax.swing.JLabel();
        txtHomeCity = new javax.swing.JTextField();
        lblHomeState = new javax.swing.JLabel();
        txtHomeState = new javax.swing.JTextField();
        lblHomeZipcode = new javax.swing.JLabel();
        txtHomeZipCode = new javax.swing.JTextField();
        txtWorkCity = new javax.swing.JTextField();
        lblWorkState = new javax.swing.JLabel();
        txtWorkState = new javax.swing.JTextField();
        lblWorkZipcode = new javax.swing.JLabel();
        txtWorkZipCode = new javax.swing.JTextField();
        lblWorkAdrHeader = new javax.swing.JLabel();
        lblWorkStreetAdr = new javax.swing.JLabel();
        txtWorkStreetAdr = new javax.swing.JTextField();
        lblWorkUnitNum = new javax.swing.JLabel();
        txtWorkUnitNum = new javax.swing.JTextField();
        lblWorkCity = new javax.swing.JLabel();
        btnCreatePerson = new javax.swing.JButton();

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 255, 204));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Create Person");

        lblLastName.setBackground(new java.awt.Color(255, 255, 255));
        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLastName.setText("Last Name:");

        lblFirstName.setBackground(new java.awt.Color(255, 255, 255));
        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFirstName.setText("First Name:");

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        lblGender.setBackground(new java.awt.Color(255, 255, 255));
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGender.setText("Gender:");

        lblAge.setBackground(new java.awt.Color(255, 255, 255));
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAge.setText("Age:");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        lblSSN.setBackground(new java.awt.Color(255, 255, 255));
        lblSSN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSSN.setText("SSN:");

        lblLicenseNum.setBackground(new java.awt.Color(255, 255, 255));
        lblLicenseNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLicenseNum.setText("License Number:");

        txtLicenseNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseNumActionPerformed(evt);
            }
        });

        lblHomeAdrHeader.setBackground(new java.awt.Color(255, 255, 255));
        lblHomeAdrHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHomeAdrHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomeAdrHeader.setText("Home Address");

        lblHomeStreetAdr.setBackground(new java.awt.Color(255, 255, 255));
        lblHomeStreetAdr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHomeStreetAdr.setText("Street Address:");

        lblHomeUnitNum.setBackground(new java.awt.Color(255, 255, 255));
        lblHomeUnitNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHomeUnitNum.setText("Unit Number:");

        txtHomeUnitNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHomeUnitNumActionPerformed(evt);
            }
        });

        lblHomeCity.setBackground(new java.awt.Color(255, 255, 255));
        lblHomeCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHomeCity.setText("City:");

        lblHomeState.setBackground(new java.awt.Color(255, 255, 255));
        lblHomeState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHomeState.setText("State:");

        txtHomeState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHomeStateActionPerformed(evt);
            }
        });

        lblHomeZipcode.setBackground(new java.awt.Color(255, 255, 255));
        lblHomeZipcode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHomeZipcode.setText("Zipcode:");

        lblWorkState.setBackground(new java.awt.Color(255, 255, 255));
        lblWorkState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWorkState.setText("State:");

        txtWorkState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWorkStateActionPerformed(evt);
            }
        });

        lblWorkZipcode.setBackground(new java.awt.Color(255, 255, 255));
        lblWorkZipcode.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWorkZipcode.setText("Zipcode:");

        txtWorkZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWorkZipCodeActionPerformed(evt);
            }
        });

        lblWorkAdrHeader.setBackground(new java.awt.Color(255, 255, 255));
        lblWorkAdrHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWorkAdrHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWorkAdrHeader.setText("Work Address");

        lblWorkStreetAdr.setBackground(new java.awt.Color(255, 255, 255));
        lblWorkStreetAdr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWorkStreetAdr.setText("Street Address:");

        lblWorkUnitNum.setBackground(new java.awt.Color(255, 255, 255));
        lblWorkUnitNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWorkUnitNum.setText("Unit Number:");

        txtWorkUnitNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWorkUnitNumActionPerformed(evt);
            }
        });

        lblWorkCity.setBackground(new java.awt.Color(255, 255, 255));
        lblWorkCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWorkCity.setText("City:");

        btnCreatePerson.setText("Create Person");
        btnCreatePerson.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHomeAdrHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHomeZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHomeZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblWorkAdrHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHomeCity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHomeCity, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblHomeState, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHomeStreetAdr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHomeStreetAdr, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblHomeUnitNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHomeUnitNum, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHomeState, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblWorkStreetAdr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtWorkStreetAdr, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(lblWorkUnitNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblWorkZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblWorkCity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtWorkZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtWorkCity, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblWorkState, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtWorkUnitNum)
                                    .addComponent(txtWorkState, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCreatePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(366, 366, 366))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHomeAdrHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeStreetAdr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeStreetAdr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHomeUnitNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeUnitNum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeCity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHomeState, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeState, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWorkAdrHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWorkStreetAdr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWorkStreetAdr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWorkUnitNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWorkUnitNum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtWorkCity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtWorkState, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblWorkState, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblWorkCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWorkZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWorkZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnCreatePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtLicenseNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseNumActionPerformed

    private void txtHomeUnitNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHomeUnitNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHomeUnitNumActionPerformed

    private void txtHomeStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHomeStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHomeStateActionPerformed

    private void txtWorkStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWorkStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWorkStateActionPerformed

    private void txtWorkUnitNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWorkUnitNumActionPerformed

    }//GEN-LAST:event_txtWorkUnitNumActionPerformed

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        // TODO add your handling code here:
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String ageStr = txtAge.getText();
        String gender = txtGender.getText();
        String ssn = txtSSN.getText();
        String license_number = txtLicenseNum.getText();
        
        // Home address
        String homeStreetAdr = txtHomeStreetAdr.getText();
        String homeUnitNum = txtHomeUnitNum.getText();
        String homeCity = txtHomeCity.getText();
        String homeState = txtHomeState.getText();
        String homeZipcode = txtHomeZipCode.getText();
        
        // Work address
        String workStreetAdr = txtWorkStreetAdr.getText();
        String workUnitNum = txtWorkUnitNum.getText();
        String workCity = txtWorkCity.getText();
        String workState = txtWorkState.getText();
        String workZipcode = txtWorkZipCode.getText();
        
        // Validation for NO empty fields
        if(firstName.trim().isEmpty() || lastName.trim().isEmpty() || ageStr.trim().isEmpty() || gender.trim().isEmpty() || ssn.trim().isEmpty() || license_number.trim().isEmpty()
                || homeStreetAdr.trim().isEmpty() || homeUnitNum.trim().isEmpty() || homeCity.trim().isEmpty() || homeState.trim().isEmpty() || homeZipcode.trim().isEmpty()
                || workStreetAdr.trim().isEmpty() || workUnitNum.trim().isEmpty() || workCity.trim().isEmpty() || workState.trim().isEmpty() || workZipcode.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter details in all fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate first name does not contain integers
        if (firstName.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(null, "Enter valid first name", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        // Validate last name does not contain integers
        if (lastName.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(null, "Enter valid last name", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        // Validate home zipcode number has 5 digits only
        if (!homeZipcode.matches("\\d{5}")){
            JOptionPane.showMessageDialog(null, "Enter valid 5-digit home zipcode", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        // Validate work zipcode number has 5 digits only
        if (!workZipcode.matches("\\d{5}")){
            JOptionPane.showMessageDialog(null, "Enter valid 5-digit work zipcode", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        // Validate ssn has 9 digits only
        if (!ssn.matches("\\d{9}")){
            JOptionPane.showMessageDialog(null, "Enter valid 9-digit ssn", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        // Validate license number has 9 digits only
        if (!license_number.matches("\\d{9}")){
            JOptionPane.showMessageDialog(null, "Enter valid 9-digit license number", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        

        int age = Integer.parseInt(ageStr);
        
        Person person = personDirectory.addPerson();
        
        person.setFirstName(firstName);
        person.setLastName(lastName);
        person.setGender(gender);
        person.setAge(age);
        person.setSsn(ssn);
        person.setLicense_number(license_number);
        person.getHomeadr().setStreetAdr(homeStreetAdr);
        person.getHomeadr().setUnitNum(homeUnitNum);
        person.getHomeadr().setCity(homeCity);
        person.getHomeadr().setState(homeState);
        person.getHomeadr().setZipCode(homeZipcode);
        person.getWorkadr().setStreetAdr(workStreetAdr);
        person.getWorkadr().setUnitNum(workUnitNum);
        person.getWorkadr().setCity(workCity);
        person.getWorkadr().setState(workState);
        person.getWorkadr().setZipCode(workZipcode);
        
        JOptionPane.showMessageDialog(null, "Person Profile Successfully Created");
        
        txtFirstName.setText("");
        txtLastName.setText("");
        txtAge.setText("");
        txtGender.setText("");
        txtSSN.setText("");
        txtLicenseNum.setText("");
        txtHomeStreetAdr.setText("");
        txtHomeUnitNum.setText("");
        txtHomeCity.setText("");
        txtHomeState.setText("");
        txtHomeZipCode.setText("");
        txtWorkStreetAdr.setText("");
        txtWorkUnitNum.setText("");
        txtWorkCity.setText("");
        txtWorkState.setText("");
        txtWorkZipCode.setText("");
        
    }//GEN-LAST:event_btnCreatePersonActionPerformed

    private void txtWorkZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWorkZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWorkZipCodeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHomeAdrHeader;
    private javax.swing.JLabel lblHomeCity;
    private javax.swing.JLabel lblHomeState;
    private javax.swing.JLabel lblHomeStreetAdr;
    private javax.swing.JLabel lblHomeUnitNum;
    private javax.swing.JLabel lblHomeZipcode;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLicenseNum;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblWorkAdrHeader;
    private javax.swing.JLabel lblWorkCity;
    private javax.swing.JLabel lblWorkState;
    private javax.swing.JLabel lblWorkStreetAdr;
    private javax.swing.JLabel lblWorkUnitNum;
    private javax.swing.JLabel lblWorkZipcode;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHomeCity;
    private javax.swing.JTextField txtHomeState;
    private javax.swing.JTextField txtHomeStreetAdr;
    private javax.swing.JTextField txtHomeUnitNum;
    private javax.swing.JTextField txtHomeZipCode;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLicenseNum;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWorkCity;
    private javax.swing.JTextField txtWorkState;
    private javax.swing.JTextField txtWorkStreetAdr;
    private javax.swing.JTextField txtWorkUnitNum;
    private javax.swing.JTextField txtWorkZipCode;
    // End of variables declaration//GEN-END:variables
}


