/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.RoleSelection;

import Business.Course.Course;
import java.awt.CardLayout;
import Business.Course.CourseList;
import Business.Degree.DegreeList;
import Business.Professor.Professor;
import Business.Professor.ProfessorList;
import Business.ProfessorLogin.ProfessorLogin;
import Business.ProfessorLogin.ProfessorLoginList;
import Business.Semester.Semester;
import Business.Semester.SemesterList;
import Business.Student.Student;
import Business.Student.StudentList;
import Business.StudentLogin.StudentLogin;
import Business.StudentLogin.StudentLoginList;
import UserInterface.RoleSelection.Admin.AdminLoginPanel;
import UserInterface.RoleSelection.Professor.ProfessorLoginPanel;
import UserInterface.RoleSelection.Student.StudentLoginPanel;
import java.util.HashMap;
import java.util.List;

/**
 *
 * @author nasik
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    Semester sem;
    SemesterList semlist;
    ProfessorList professorList;
    ProfessorLoginList professorLoginList;
    CourseList courseList;
    StudentList studentList;
    StudentLoginList studentLoginList;
    HashMap<String, List<Course>> studentCour;
    HashMap<Semester, List<Course>> semCourses;
    DegreeList degreeList;

    public MainJFrame() {
        initComponents();
        this.sem = sem;
        this.semlist = semlist;
        this.professorList= new ProfessorList();
        this.professorLoginList= new ProfessorLoginList();
        this.courseList = new CourseList();
        this.studentList = new StudentList();
        this.studentLoginList = new StudentLoginList();
        this.studentCour = new HashMap<>();
        this.semCourses = new HashMap<>();
        this.degreeList = new DegreeList();
        
        initializeStudentData(); 
        initializeProfessorData();
        prePopulateCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnAdmin = new javax.swing.JButton();
        btnProfessor = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setBackground(new java.awt.Color(255, 204, 204));

        btnAdmin.setBackground(new java.awt.Color(204, 204, 255));
        btnAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        btnProfessor.setBackground(new java.awt.Color(204, 204, 255));
        btnProfessor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProfessor.setText("Professor");
        btnProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfessorActionPerformed(evt);
            }
        });

        btnStudent.setBackground(new java.awt.Color(204, 204, 255));
        btnStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStudent.setText("Student");
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("University Model");

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addComponent(btnStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblTitle)
                .addGap(69, 69, 69)
                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProfessor)
                .addGap(18, 18, 18)
                .addComponent(btnStudent)
                .addContainerGap(336, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(controlPanel);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        AdminLoginPanel adminPanel = new AdminLoginPanel(userProcessContainer, professorList, professorLoginList, courseList, studentList, studentLoginList, studentCour,degreeList);
        userProcessContainer.add("AdminPanel",adminPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessorActionPerformed
        // TODO add your handling code here:
        ProfessorLoginPanel profLogin = new ProfessorLoginPanel(userProcessContainer, professorList,professorLoginList, courseList, studentList, studentLoginList,  studentCour, degreeList);
        userProcessContainer.add("ProfessorLoginPanel",profLogin);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProfessorActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
        StudentLoginPanel studentPanel = new StudentLoginPanel(userProcessContainer, professorList, professorLoginList, courseList, studentList, studentLoginList,  studentCour,degreeList);
        userProcessContainer.add("StudentLoginPanel",studentPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnStudentActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
            
        });
         
    }
    
    private void initializeSems(){
        Semester s1 = semlist.addSemester("Fall'24");
    }
    
     private void initializeStudentData() {
          for (int i = 1; i <= 10; i++) {
        String studentID = "ID" + i;
        String studentName = "Student_" + i;
        String studentEmail = "email" + i + "@example.com";
        String studentUsername = "nuid" + i;
        String studentPassword = "pass" + i;

        Student student = studentList.addNewStudent();
        student.setStudentID(studentID);
        student.setStudentName(studentName);
        student.setStudentEmail(studentEmail);

        StudentLogin studentLogin = studentLoginList.addNewStudentLogin();
        studentLogin.setStudentUsername(studentUsername);
        studentLogin.setStudentPassword(studentPassword);
    }
    }

    
    private void initializeProfessorData() {
          for (int i = 1; i <= 10; i++) {
        String profId = "Prof" + i;
        String profName = "Professor_" + i;
        String profEmail = "prof" + i + "@university.com";
        String profUsername = "prof" + i;
        String profPassword = "pass" + i;

        Professor professor = professorList.addNewProfessor();
        professor.setProfId(profId);
        professor.setProfName(profName);
        professor.setProfEmail(profEmail);

        ProfessorLogin profLogin = professorLoginList.addNewProfessorLogin();
        profLogin.setProfUsername(profUsername);
        profLogin.setProfPassword(profPassword);
    }
}

     private void prePopulateCourses() {
        Course c1 = courseList.addNewCourse();
        c1.setCourseId("1");
        c1.setCourseName("Introduction to Computer Science");
        c1.setProfCName("Professor_1");
        c1.setCoursePrice("$1200"); 
        c1.setCourseDuration("10 weeks");
        c1.setCredits("4");
        c1.setCourseType("Core");

        Course c2 = courseList.addNewCourse();
        c2.setCourseId("2");
        c2.setCourseName("Advanced Calculus");
        c2.setProfCName("Professor_2");
        c2.setCoursePrice("$1500");
        c2.setCourseDuration("12 weeks");
        c2.setCredits("4");
        c2.setCourseType("Core");

        Course c3 = courseList.addNewCourse();
        c3.setCourseId("3");
        c3.setCourseName("Classical Mechanics");
        c3.setProfCName("Professor_3");
        c3.setCoursePrice("$1300");
        c3.setCourseDuration("11 weeks");
        c3.setCredits("4");
        c3.setCourseType("Core");

        Course c4 = courseList.addNewCourse();
        c4.setCourseId("4");
        c4.setCourseName("General Chemistry");
        c4.setProfCName("Professor_4");
        c4.setCoursePrice("$1400");
        c4.setCourseDuration("10 weeks");
        c4.setCredits("4");
        c4.setCourseType("Elective");

        Course c5 = courseList.addNewCourse();
        c5.setCourseId("5");
        c5.setCourseName("Modern English Literature");
        c5.setProfCName("Professor_5");
        c5.setCoursePrice("$1100");
        c5.setCourseDuration("8 weeks");
        c5.setCredits("3");
        c5.setCourseType("Elective");

        Course c6 = courseList.addNewCourse();
        c6.setCourseId("6");
        c6.setCourseName("Molecular Biology");
        c6.setProfCName("Professor_6");
        c6.setCoursePrice("$1600");
        c6.setCourseDuration("12 weeks");
        c6.setCredits("4");
        c6.setCourseType("Elective");

        Course c7 = courseList.addNewCourse();
        c7.setCourseId("7");
        c7.setCourseName("Introduction to Psychology");
        c7.setProfCName("Professor_7");
        c7.setCoursePrice("$1100");
        c7.setCourseDuration("8 weeks");
        c7.setCredits("3");
        c7.setCourseType("Elective");

        Course c8 = courseList.addNewCourse();
        c8.setCourseId("8");
        c8.setCourseName("World History");
        c8.setProfCName("Professor_8");
        c8.setCoursePrice("$1500");
        c8.setCourseDuration("10 weeks");
        c8.setCredits("4");
        c8.setCourseType("Elective");

        Course c9 = courseList.addNewCourse();
        c9.setCourseId("9");
        c9.setCourseName("Art Appreciation");
        c9.setProfCName("Professor_9");
        c9.setCoursePrice("$1000");
        c9.setCourseDuration("6 weeks");
        c9.setCredits("2");
        c9.setCourseType("Elective");

        Course c10 = courseList.addNewCourse();
        c10.setCourseId("10");
        c10.setCourseName("Artificial Intelligence");
        c10.setProfCName("Professor_10");
        c10.setCoursePrice("$2000");
        c10.setCourseDuration("14 weeks");
        c10.setCredits("4");
        c10.setCourseType("Elective");

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnProfessor;
    private javax.swing.JButton btnStudent;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
